data_params:
    tokenizer_hf_path: 'elderberry17/silly-sentence-bert'
    mlm_probability: 0.15
    data_path_ru: 'yandex_translate_corpus/texts_ru.txt'
    data_path_en: 'yandex_translate_corpus/texts_en.txt'
    train_size: 0.8
    train_bs: 2
    test_bs: 2
    max_seq_len: 128

bebert_params:
    model_dim: 256
    n_blocks: 6
    n_heads: 4

trainer_params:
    lr: 0.0001
    weight_decay: 0.01
    beta1: 0.9
    beta2: 0.999
    warmup_steps: 10000
    log_freq: 100
    device: 'cpu'
    # checkpoint_dir: 'checkpoints_nsp'
    checkpoint_dir: 'checkpoints_mlm'

    # train_task: 'nsp'
    train_task: 'mlm'

    num_epochs: 3