model_name: 'elderberry17/silly-sentence-bert'
benchmark_names:
  - 'GeoreviewClassification'
  - 'GeoreviewClusteringP2P'
  - 'HeadlineClassification'
  - 'InappropriatenessClassification'
  - 'KinopoiskClassification'
  - 'RiaNewsRetrieval'
  - 'RuBQRetrieval'
  - 'RuReviewsClassification'
  - 'RuSciBenchGRNTIClassification'
  - 'RuSciBenchGRNTIClusteringP2P'
  - 'RuSciBenchOECDClassification'
  - 'RuSciBenchOECDClusteringP2P'
  - 'RuSTSBenchmarkSTS'
  - 'TERRa'
  - 'RuBQReranking'
  - 'CEDRClassification'
  - 'SensitiveTopicsClassification'

output_folder: 'mteb_test/results'
